In [4]:
def describe(x):
    print(f"Type: {x.type}")
    print(f"Shape/size: {x.shape}")
    print(f"Values: {x}")

In [2]:
import torch

In [5]:
describe(torch.Tensor(2,3))

Type: <built-in method type of Tensor object at 0x000002D78D421868>
Shape/size: torch.Size([2, 3])
Values: tensor([[0.0000e+00, 8.4490e-39, 1.6707e-07],
        [2.5930e-09, 1.3109e-08, 2.1956e-04]])


In [6]:
describe(torch.rand(2,3))

Type: <built-in method type of Tensor object at 0x000002D78D4C1368>
Shape/size: torch.Size([2, 3])
Values: tensor([[0.5130, 0.5229, 0.3506],
        [0.9963, 0.6880, 0.9266]])


In [7]:
describe(torch.randn(2,3))

Type: <built-in method type of Tensor object at 0x000002D78D6F9CC8>
Shape/size: torch.Size([2, 3])
Values: tensor([[-0.7874, -0.5163, -0.0198],
        [-0.1243,  0.3140, -1.2744]])


In [9]:
x = torch.ones(2,3)

In [10]:
describe(x)

Type: <built-in method type of Tensor object at 0x000002D78D6AA9A8>
Shape/size: torch.Size([2, 3])
Values: tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [11]:
x.fill_(5)

tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [12]:
import numpy

In [13]:
npy = numpy.random.rand(2,3)

In [14]:
describe(torch.from_numpy(npy))

Type: <built-in method type of Tensor object at 0x000002D78D7E7368>
Shape/size: torch.Size([2, 3])
Values: tensor([[0.4343, 0.1940, 0.9931],
        [0.0307, 0.1739, 0.9864]], dtype=torch.float64)


In [15]:
describe(torch.FloatTensor(2,3))

Type: <built-in method type of Tensor object at 0x000002D78D4BEA48>
Shape/size: torch.Size([2, 3])
Values: tensor([[5.4655e+22, 2.0450e+23, 4.2052e-05],
        [1.6779e+22, 5.2345e-11, 7.1450e+31]])


In [16]:
x = x.long()

In [17]:
describe(x)

Type: <built-in method type of Tensor object at 0x000002D78D9EE548>
Shape/size: torch.Size([2, 3])
Values: tensor([[5, 5, 5],
        [5, 5, 5]])


In [26]:
x = torch.tensor([[1, 2, 3],[4, 5, 6]], dtype=torch.int64)

In [27]:
describe(x)

Type: <built-in method type of Tensor object at 0x000002D78D238F48>
Shape/size: torch.Size([2, 3])
Values: tensor([[1, 2, 3],
        [4, 5, 6]])


In [28]:
x = x.float()

In [29]:
describe(x)

Type: <built-in method type of Tensor object at 0x000002D78D7282C8>
Shape/size: torch.Size([2, 3])
Values: tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [30]:
describe(x+x)

Type: <built-in method type of Tensor object at 0x000002D78DB114A8>
Shape/size: torch.Size([2, 3])
Values: tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [31]:
describe(torch.add(x,x))

Type: <built-in method type of Tensor object at 0x000002D78D429908>
Shape/size: torch.Size([2, 3])
Values: tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [32]:
describe(torch.add(x,-x))

Type: <built-in method type of Tensor object at 0x000002D78D7054F8>
Shape/size: torch.Size([2, 3])
Values: tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [33]:
describe(x)

Type: <built-in method type of Tensor object at 0x000002D78D7282C8>
Shape/size: torch.Size([2, 3])
Values: tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [34]:
x = torch.arange(6)

In [35]:
describe(x)

Type: <built-in method type of Tensor object at 0x000002D78D421818>
Shape/size: torch.Size([6])
Values: tensor([0, 1, 2, 3, 4, 5])


In [36]:
x = x.view(2,3)

In [37]:
describe(x)

Type: <built-in method type of Tensor object at 0x000002D78D9E1868>
Shape/size: torch.Size([2, 3])
Values: tensor([[0, 1, 2],
        [3, 4, 5]])


In [38]:
describe(torch.sum(x, dim=0))

Type: <built-in method type of Tensor object at 0x000002D78DA3A458>
Shape/size: torch.Size([3])
Values: tensor([3, 5, 7])


In [39]:
describe(torch.sum(x, dim = 1))

Type: <built-in method type of Tensor object at 0x000002D78D95C0E8>
Shape/size: torch.Size([2])
Values: tensor([ 3, 12])


In [46]:
describe(torch.transpose(x, 0, 1))

Type: <built-in method type of Tensor object at 0x000002D78D741E08>
Shape/size: torch.Size([3, 2])
Values: tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [156]:
x = torch.arange(6).view(2,3)

In [157]:
describe(x)

Type: <built-in method type of Tensor object at 0x000002D78DA29F48>
Shape/size: torch.Size([2, 3])
Values: tensor([[0, 1, 2],
        [3, 4, 5]])


In [158]:
describe(x[:1, :2])

Type: <built-in method type of Tensor object at 0x000002D78D72C908>
Shape/size: torch.Size([1, 2])
Values: tensor([[0, 1]])


In [159]:
describe(x[0,2])

Type: <built-in method type of Tensor object at 0x000002D78DA45048>
Shape/size: torch.Size([])
Values: 2


In [170]:
indices = torch.LongTensor([2])

In [171]:
describe(indices)

Type: <built-in method type of Tensor object at 0x000002D78DA43408>
Shape/size: torch.Size([1])
Values: tensor([2])


In [174]:
describe(torch.index_select(x, dim=1 ,index=indices))

Type: <built-in method type of Tensor object at 0x000002D78D4C5C78>
Shape/size: torch.Size([2, 1])
Values: tensor([[2],
        [5]])


In [166]:
describe(torch.cat([x,x], dim = 1))

Type: <built-in method type of Tensor object at 0x000002D78D440958>
Shape/size: torch.Size([2, 6])
Values: tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [66]:
describe(torch.stack([x,x]))

Type: <built-in method type of Tensor object at 0x000002D78DB5C048>
Shape/size: torch.Size([2, 2, 3])
Values: tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [68]:
describe(torch.mm(x,x.T))

Type: <built-in method type of Tensor object at 0x000002D78D918E08>
Shape/size: torch.Size([2, 2])
Values: tensor([[ 5, 14],
        [14, 50]])


In [69]:
x = torch.ones(2,2, requires_grad = True)

In [70]:
describe(x)

Type: <built-in method type of Tensor object at 0x000002D78D4F5EA8>
Shape/size: torch.Size([2, 2])
Values: tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [79]:
y = x + x + 3

In [80]:
describe(y)

Type: <built-in method type of Tensor object at 0x000002D78DA3A638>
Shape/size: torch.Size([2, 2])
Values: tensor([[5., 5.],
        [5., 5.]], grad_fn=<AddBackward0>)


In [81]:
print(x.grad is None)

False


In [82]:
z = y.mean()

In [83]:
describe(z)

Type: <built-in method type of Tensor object at 0x000002D78DA247C8>
Shape/size: torch.Size([])
Values: 5.0


In [84]:
z.backward()

In [89]:
describe(z)

Type: <built-in method type of Tensor object at 0x000002D78DA247C8>
Shape/size: torch.Size([])
Values: 5.0


In [110]:
x = torch.rand(3,3)

In [111]:
x.squeeze(0)

tensor([[0.1358, 0.2269, 0.3176],
        [0.1695, 0.7402, 0.4977],
        [0.6009, 0.7184, 0.0270]])

In [117]:
x.squeeze(0)

tensor([[0.1358, 0.2269, 0.3176],
        [0.1695, 0.7402, 0.4977],
        [0.6009, 0.7184, 0.0270]])

In [118]:
x = torch.rand(5,3) * (7-3)

In [120]:
x+3

tensor([[3.5250, 6.3873, 3.3723],
        [5.5428, 4.4480, 6.4266],
        [6.3128, 4.3291, 4.8451],
        [5.6264, 4.8943, 6.5023],
        [5.1817, 6.2775, 5.1411]])

In [121]:
x = torch.rand(3,3)

In [122]:
x.normal_()

tensor([[-0.3327,  0.5562, -0.0177],
        [ 0.7152,  0.0305, -1.5745],
        [-0.8261,  0.1569, -0.7685]])

In [123]:
x

tensor([[-0.3327,  0.5562, -0.0177],
        [ 0.7152,  0.0305, -1.5745],
        [-0.8261,  0.1569, -0.7685]])

In [124]:
x = torch.Tensor([1,1,1,0,1])

In [126]:
torch.nonzero(x)

tensor([[0],
        [1],
        [2],
        [4]])

In [133]:
x = torch.rand(3,1)

In [134]:
x

tensor([[0.7754],
        [0.3959],
        [0.6027]])

In [135]:
torch.stack([x,x,x,x])

tensor([[[0.7754],
         [0.3959],
         [0.6027]],

        [[0.7754],
         [0.3959],
         [0.6027]],

        [[0.7754],
         [0.3959],
         [0.6027]],

        [[0.7754],
         [0.3959],
         [0.6027]]])

In [136]:
x.expand(3,4)

tensor([[0.7754, 0.7754, 0.7754, 0.7754],
        [0.3959, 0.3959, 0.3959, 0.3959],
        [0.6027, 0.6027, 0.6027, 0.6027]])

In [138]:
torch.bmm(torch.rand(3,4,5), torch.rand(3,5,4))

tensor([[[1.6549, 1.3594, 1.6028, 1.1478],
         [1.1855, 0.9202, 0.8705, 0.9369],
         [1.7832, 1.5176, 1.7441, 1.3054],
         [1.7754, 1.7427, 1.7502, 1.3393]],

        [[1.5018, 1.2781, 0.5228, 0.4812],
         [1.9968, 1.9048, 0.6118, 0.3843],
         [2.6568, 2.0353, 1.0162, 0.8014],
         [1.3995, 1.1533, 0.6835, 0.5961]],

        [[1.4874, 1.6978, 1.7642, 2.0508],
         [1.2484, 1.4260, 1.0982, 1.2463],
         [0.9504, 1.0635, 0.9944, 1.1503],
         [0.6234, 1.2602, 0.6877, 1.2680]]])

In [142]:
a = torch.rand(3, 4, 5)
b = torch.rand(5, 4)
torch.bmm(a, b.expand(a.size(0), *b.size()))

tensor([[[0.6004, 1.7837, 1.6496, 2.3260],
         [0.6441, 2.0735, 1.4010, 2.7144],
         [0.3150, 1.0439, 0.9765, 1.6151],
         [0.5102, 1.6235, 0.9052, 2.0104]],

        [[0.5616, 1.7374, 0.9266, 1.7686],
         [0.4137, 1.2623, 1.0078, 1.6953],
         [0.4320, 1.3581, 0.6407, 1.4461],
         [0.5176, 1.6278, 1.0889, 2.0863]],

        [[0.3864, 1.2111, 1.0273, 1.8211],
         [0.7471, 2.3210, 1.5506, 2.8826],
         [0.5508, 1.8074, 1.0441, 2.1704],
         [0.5404, 1.5798, 1.1255, 1.5956]]])

In [140]:
a

tensor([[[0.7100, 0.2905, 0.0771, 0.8971, 0.7379],
         [0.5479, 0.6645, 0.2608, 0.3122, 0.0673],
         [0.8552, 0.7433, 0.7554, 0.7703, 0.2785],
         [0.4541, 0.7287, 0.3093, 0.5308, 0.1232]],

        [[0.2105, 0.8804, 0.7780, 0.8614, 0.0092],
         [0.9740, 0.4743, 0.1083, 0.2189, 0.9534],
         [0.2042, 0.9509, 0.6240, 0.0429, 0.2219],
         [0.9859, 0.1636, 0.3454, 0.2983, 0.7941]],

        [[0.1723, 0.6417, 0.0968, 0.3963, 0.2702],
         [0.6628, 0.7696, 0.2761, 0.1509, 0.1684],
         [0.6885, 0.9057, 0.9417, 0.9195, 0.6765],
         [0.3113, 0.7531, 0.4717, 0.3319, 0.9580]]])

In [141]:
b

tensor([[0.0361, 0.2371, 0.3500, 0.5547],
        [0.9741, 0.7679, 0.7570, 0.0903],
        [0.8978, 0.0559, 0.1443, 0.5962],
        [0.4092, 0.3096, 0.7988, 0.2525],
        [0.6854, 0.4779, 0.7699, 0.6664]])